/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LISTDIR_H_RPCGEN
#define _LISTDIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef char *nametype;

typedef struct namenode *namelist;

struct namenode {
	nametype name;
	namelist next;
};
typedef struct namenode namenode;

struct readdir_ret {
	int err;
	union {
		namelist list;
	} readdir_ret_u;
};
typedef struct readdir_ret readdir_ret;

#define DIR_LIST_PROG 0x20000026
#define DIR_LIST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define READDIR 1
extern  readdir_ret * readdir_1(nametype *, CLIENT *);
extern  readdir_ret * readdir_1_svc(nametype *, struct svc_req *);
extern int dir_list_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READDIR 1
extern  readdir_ret * readdir_1();
extern  readdir_ret * readdir_1_svc();
extern int dir_list_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_namelist (XDR *, namelist*);
extern  bool_t xdr_namenode (XDR *, namenode*);
extern  bool_t xdr_readdir_ret (XDR *, readdir_ret*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_namelist ();
extern bool_t xdr_namenode ();
extern bool_t xdr_readdir_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LISTDIR_H_RPCGEN */
